### ISSUE TITLE
notears_nonlinear.py seems to miss notears_nonlinear function. 

### ISSUE THREAD

**Issue by ling-k** [Information-Fusion-Lab-Umass/causal_transfer_learning#1]
I spent some time running your code but it seems like that the causal dynamics learning part is not working. In particular, codes/data/notears_nonlinear.py seems to miss notears_nonlinear function. 
Could you please have a look? 
Thanks so much.

**Comment by purvapruthi** [comment]
Thanks for bringing this to my attention. I have updated the file to include the function. I might have uploaded an older version of the file. Let me know if there is any other issue in running the code.
